# SARSA

In [38]:
import gym
import numpy as np
import pygame

In [39]:
env = gym.make("FrozenLake-v1")

print("Action space: ", env.action_space)
print("Observation space: ", env.observation_space)

Action space:  Discrete(4)
Observation space:  Discrete(16)


In [40]:
n_actions = env.action_space.n
n_states = env.observation_space.n

#Initialisation pour tous les états s et actions a
Q = np.zeros((n_states, n_actions))     
print(Q)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [51]:
#On définit les hyperparamètres
alpha = 0.1 #Taux d'apprentissage
gamma = 0.99 #Facteur d'escompte
epsilon = 0.1 #Paramètre d'exploration
total_episodes = 10000 
max_steps = 100 #nb de steps par episode


#On définit la politique epsilon-greedy
def epsilon_greedy_policy(Q, state, epsilon):
    if np.random.uniform(0,1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])

        
#On initialise le reward
reward = 0


#Loop pour chaque épisode
for episode in range(total_episodes):
    
    #On initialise s
    
    if convert_state_to_int is None:
        convert_state_to_int = lambda state: state
        
    state, _ = env.reset()
    s = convert_state_to_int(state)
  
    #On choisit l'action à partir de s en utilisant epsilon_greedy
    action = epsilon_greedy_policy(Q, s, epsilon)
    
    
    #Loop pour chaque step dans épisode     
    for step in range(max_steps):
        
        #On prend l'action a
        next_state, reward, terminated, truncated, _  = env.step(action)
        next_s = convert_state_to_int(next_state)
            
        #On choisir a' à partir de s' en utilisant la politique epsilon-greedy
        next_a = epsilon_greedy_policy(Q, state, epsilon)
        
        #Mise à jour de la table Q
        Q[s,a] = (1-alpha)*Q[s,a] + alpha*(reward + (gamma*Q[next_s,next_a]))
            
        s = nex_s
        a = next_a
        
        history["rewards"][episode] += reward
        history["moves"][episode] += 1
                
        if terminated or truncated:
            break

KeyError: None